name: Library

on: [pull_request]

env:
  RUST_LOG: "0"

jobs:
  library:
    name: library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check
        run: cargo check
      - name: Install webassembly target
        run: rustup target add wasm32-unknown-unknown
      - name: Check webassembly
        run: cargo check --target wasm32-unknown-unknown
      - name: Check cargo fmt
        run: cargo fmt --all -- --check
      - name: Check cargo clippy
        run: cargo clippy
      - name: Run tests
        run: cargo test
